apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: frontend






# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend
# spec:
#   type: NodePort
#   ports:
#   - protocol: TCP
#     port: 80  
#     targetPort: 8080
#     nodePort: 30001
#   selector:
#     app: frontend
  # annotations:
  #   service.kubernetes.io/load-balancer-type: "alb"  
  #   alb.ingress.kubernetes.io/scheme: internet-facing 
  #   alb.ingress.kubernetes.io/target-type: ip 